matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.3
      script:
        - swift package generate-xcodeproj && xcodebuild clean test -project GeoKit.xcodeproj -scheme GeoKit-Package -enableCodeCoverage YES